image: microsoft/aspnetcore-build:2.0

build:
  stage: build
  script: 
    - dotnet restore
    - dotnet build

test:
  stage: test
  script: 
    - dotnet restore
    - dotnet test Sox.Core.Tests /p:CollectCoverage=true